siteTitle = 'VND Game'
siteDescr = 'Giải Trí Trong Nhà'
siteDescription = "Tôi Phạm Xuân Tiếp, tổng hợp những món đồ mà mình cần trong cuộc sống và công việc để khi đủ tiền thì rinh món đồ đó về nhà"
siteUrl = "https://vndgame.site"
siteBandcampUrl = 'https://vndgame.site'
siteMenuOne = 'Nên mua'
siteMenuTwo = 'Đã có'
siteMenuThree = 'Quan tâm'

siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/OdayakaPhuQuoc'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
